require("dotenv").config();
const connectDB = require("./configs/dbConn");
connectDB();
const express = require("express");
const cors = require("cors");
const useragent = require("express-useragent");
const port = process.env.PORT || 4000;
const app = express();
app.use(cors());
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use(useragent.express());
app.listen(port, () => {
  console.log(`Server listing on ${port}`);
});
const userRoutes = require("./routes/userRoutes");
const fileRoutes = require("./routes/fileRoutes");
const userdetailsRoutes = require("./routes/userdetailsRoutes");
app.use("/user", userRoutes);
app.use("/file", fileRoutes);
app.use("/userdetails", userdetailsRoutes);
